name: CI
on: [ push ]
jobs:
    build:
        name: Build, lint, and test
        runs-on: ubuntu-18.04
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
            -   name: Use Node 14.x
                uses: actions/setup-node@v1
                with:
                    node-version: '14.x'
            -   name: Install deps and build (with cache)
                uses: bahmutov/npm-install@v1
            -   name: Lint
                run: yarn lint
            -   name: Test
                run: yarn test --ci --coverage --maxWorkers=2
            -   name: Build
                run: yarn build

    publish:
        runs-on: ubuntu-18.04
        needs: build
        if: startsWith( github.ref, 'refs/tags/' )
        steps:
            -   uses: actions/setup-node@v1
                with:
                    node-version: '14.x'
            -   uses: actions/checkout@v1
            -   name: install dependencies
                run: yarn install
            -   name: publish new version to npm
                env:
                    NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
                run: ./.github/publish.sh
